### ISSUE TITLE
Missing script "aws_build_bit_from_cl.sh"

### ISSUE THREAD

**Issue by zwadood** [aws/aws-fpga-f1-u200#1]
The script mentioned in the documentation "aws_build_bit_from_cl.sh" cant be found in the repository

**Comment by kyyalama2** [comment]
Dear customer, Thank you so much for the feedback. The repo is updated to correct the names of the scripts to aws_build_bit_from_cl.sh as documented. Please feel free to let us know if you have any additional feedback/further questions.

Thanks

**Comment by kyyalama2** [comment]
closing the issue. Please feel free to reopen/create new one, if you need further help
